### ISSUE TITLE
安装后打包 报错

### ISSUE THREAD

**Issue by WEB-ZENG-GitHub** [cuteCloud/vue-qqmap#14]
> ` ERROR x Build failed in 25.13s 17:02:50
> 
> ERROR error during build: 17:02:50 [vite-plugin-pwa:build] [@vue/compiler-sfc] Failed to resolve import source "radix-vue".
> 
> D:/FrontEndProject/PcTerminal/xxxxxxx/packages/@core/ui-kit/shadcn-ui/src/ui/accordion/Accordion.vue 7 | } from 'radix-vue'; 8 | 9 | const props = defineProps(); | ^^^^^^^^^^^^^^^^^^ 10 | const emits = defineEmits(); 11 | file: D:/FrontEndProject/PcTerminal/xxxxxxx/packages/@core/ui-kit/shadcn-ui/src/ui/accordion/Accordion.vue at ScriptCompileContext.error (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19741:11) at importSourceToScope (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22626:16) at resolveTypeFromImport (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22579:23) at innerResolveTypeReference (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22466:14) at resolveTypeReference (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22454:20) at innerResolveTypeElements (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22055:24) at resolveTypeElements (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:21995:20) at resolveRuntimePropsFromType (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:23632:20) at extractRuntimeProps (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:23608:17) at genRuntimeProps (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:23596:18)
> 
>  ELIFECYCLE  Command failed with exit code 1.`

**Comment by WEB-ZENG-GitHub** [comment]
> ` ERROR x Build failed in 25.13s 17:02:50
> 
> ERROR error during build: 17:02:50 [vite-plugin-pwa:build] [@vue/compiler-sfc] Failed to resolve import source "radix-vue".
> 
> D:/FrontEndProject/PcTerminal/xxxxxxx/packages/@core/ui-kit/shadcn-ui/src/ui/accordion/Accordion.vue 7 | } from 'radix-vue'; 8 | 9 | const props = defineProps(); | ^^^^^^^^^^^^^^^^^^ 10 | const emits = defineEmits(); 11 | file: D:/FrontEndProject/PcTerminal/xxxxxxx/packages/@core/ui-kit/shadcn-ui/src/ui/accordion/Accordion.vue at ScriptCompileContext.error (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19741:11) at importSourceToScope (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22626:16) at resolveTypeFromImport (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22579:23) at innerResolveTypeReference (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22466:14) at resolveTypeReference (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22454:20) at innerResolveTypeElements (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:22055:24) at resolveTypeElements (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:21995:20) at resolveRuntimePropsFromType (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:23632:20) at extractRuntimeProps (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:23608:17) at genRuntimeProps (D:\FrontEndProject\PcTerminal\xxxxxxx\node_modules.pnpm@vue+compiler-sfc@3.5.13\node_modules@vue\compiler-sfc\dist\compiler-sfc.cjs.js:23596:18)
> 
>  ELIFECYCLE  Command failed with exit code 1.`
